In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Problema 1.-

Resolver el problema de $Ax=b$ para una matriz diagonal

$$
A=\left(\begin{array}{cccc}
a_{11} & & & \\
& a_{22} & & \\
& & \ddots & \\
& & & a_{n n}
\end{array}\right)
$$

In [2]:
A = np.diag(np.array([
    3,
    4,
    2,
    3
]))
b = np.array([[
    3,
    4,
    2,
    3
]]).T
print(A, '\n', b)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 2 0]
 [0 0 0 3]] 
 [[3]
 [4]
 [2]
 [3]]


In [9]:
#Solucion:
x = np.zeros((4,1))

for k in range(4):
    x[k,0] = b[k,0]/A[k,k]
print(x) 
print(A@x) #= b

[[1.]
 [1.]
 [1.]
 [1.]]
[[3.]
 [4.]
 [2.]
 [3.]]


In [7]:
for k in range(10): #[0,1,2,3..,9]
    print(k)

0
1
2
3
4
5
6
7
8
9


##### Solution:

In [13]:
x = np.zeros((A.shape[1],1))

for m in range(A.shape[0]):
    x[m,0]=b[m,0]/A[m,m]
    
print(x)

[[3.]
 [4.]
 [2.]
 [3.]]


## Problema 2.-

Resolver el problema de $Ax=b$ para una matriz superior

$$
A=\left(\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
& a_{22} & \ddots & \vdots \\
& & \ddots & \vdots \\
& & & a_{n n}
\end{array}\right)
$$

In [14]:
A = np.triu(
    np.ones((4,4))
           )
b = np.array([[
    3,
    4,
    2,
    3
]]).T
print(A, '\n', b)

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]] 
 [[3]
 [4]
 [2]
 [3]]


In [16]:
#Solucion:
x = np.zeros((4,1))

x[3,0] = b[3,0]/A[3,3]
for k in np.arange(start=2, stop=-1, step=-1):
    x[k,0] = (b[k,0] - A[k,(k+1):]@x[(k+1):,0] )/A[k,k]
    
print(x) 
print(A@x) #= b

[[-1.]
 [ 2.]
 [-1.]
 [ 3.]]
[[3.]
 [4.]
 [2.]
 [3.]]


##### Solucion:

In [23]:
x = np.zeros((A.shape[1],1))

x[-1,0] = b[-1,0]/A[-1,-1]
for m in np.arange(A.shape[0]-1, -1, -1):
    x[m,0]=(b[m,0]-A[m,(m+1):]@x[(m+1):]) /A[m,m]
    
print(A@x)

[[3.]
 [4.]
 [2.]
 [3.]]


## Problema 3

Resolver el problema de $Ax=b$ para una matriz inferior

$$
A=\left(\begin{array}{cccc}
a_{11} & & & \\
a_{21} & a_{22} & & \\
\vdots & \ddots & \ddots & \\
a_{n 1} & a_{n 2} & \cdots & a_{n n}
\end{array}\right)
$$

In [18]:
A = np.tril(
    np.ones((4,4))
           )
b = np.array([[
    3,
    4,
    2,
    3
]]).T
print(A, '\n', b)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]] 
 [[3]
 [4]
 [2]
 [3]]


In [20]:
#Solucion:
x = np.zeros((4,1))

x[0,0] = b[0,0]/A[0,0]
for k in np.arange(start=1, stop=3+1, step=1):
    x[k,0] = (b[k,0] - A[k,:k]@x[:k,0] )/A[k,k]
    
print(x) 
print(A@x) #= b

[[ 3.]
 [ 1.]
 [-2.]
 [ 1.]]
[[3.]
 [4.]
 [2.]
 [3.]]


#### Solucion

In [27]:
x = np.zeros((A.shape[1],1))

x[0,0] =  b[0,0]/A[0,0]
for m in np.arange(1, A.shape[0], 1):
    x[m,0]=(b[m,0]-A[m,:m]@x[:m])/A[m,m]
print(A@x)

[[3.]
 [4.]
 [2.]
 [3.]]


## Problema 4

Resolver

$$
\begin{aligned}
a_{11} x_{1}+a_{12} x_{2}+\cdots+a_{1 n} x_{n} &=b_{1}, \\
a_{21} x_{1}+a_{22} x_{2}+\cdots+a_{2 n} x_{n} &=b_{2}, \\
\vdots &=\vdots \\
a_{n 1} x_{1}+a_{n 2} x_{2}+\cdots+a_{n n} x_{n} &=b_{n},
\end{aligned}
$$

In [28]:
A = np.array([
              [2, 1, 1, 0],
              [0, -1, 4, 1],
              [2, 2, 0, -2],
              [1, 3, -1, 5]
])
b = np.array([[
    3,
    4,
    2,
    3
]]).T
print(A, '\n', b)

[[ 2  1  1  0]
 [ 0 -1  4  1]
 [ 2  2  0 -2]
 [ 1  3 -1  5]] 
 [[3]
 [4]
 [2]
 [3]]
