<a href="https://colab.research.google.com/github/Abrahammar997/numerico-invierno-2021/blob/main/Matrices_con_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

$$
\boldsymbol{A}=\left[\begin{array}{cccc}
2 & 1 & 1 & 0 \\
0 & -1 & 4 & 1 \\
2 & 2 & 0 & -2 \\
1 & 3 & -1 & 5
\end{array}\right], \quad \boldsymbol{B}=\left[\begin{array}{ccccc}
3 & -1 & 0 & 0 & 2 \\
7 & 1 & 0 & 0 & 2
\end{array}\right]
$$

In [33]:
A = np.array([
              [2, 1, 1, 0],
              [0, -1, 4, 1],
              [2, 2, 0, -2],
              [1, 3, -1, 5]
])

B = np.array([
              [3, -1, 0, 0, 2],
              [7, 1, 0, 0, 2]
])

v = np.array([np.pi, np.e, 7, 7])

print('A=\n',A,'\n')
print('B=\n',B,'\n')
print('v=\n',v,'\n')

A=
 [[ 2  1  1  0]
 [ 0 -1  4  1]
 [ 2  2  0 -2]
 [ 1  3 -1  5]] 

B=
 [[ 3 -1  0  0  2]
 [ 7  1  0  0  2]] 

v=
 [3.14159265 2.71828183 7.         7.        ] 



In [26]:
#A.shape
#A.size

In [34]:
print('A\n','renglones=',A.shape[0],', columnas=',A.shape[1],'\n')
print('B\n','renglones=',B.shape[0],', columnas=',B.shape[1],'\n')
print('v=\n',v.shape,'\n')

A
 renglones= 4 , columnas= 4 

B
 renglones= 2 , columnas= 5 

v=
 (4,) 



In [41]:
v = np.resize(v,new_shape=(v.size,1))
print(v)

[[3.14159265]
 [2.71828183]
 [7.        ]
 [7.        ]]


In [43]:
np.concatenate((A,v),axis=1)

array([[ 2.        ,  1.        ,  1.        ,  0.        ,  3.14159265],
       [ 0.        , -1.        ,  4.        ,  1.        ,  2.71828183],
       [ 2.        ,  2.        ,  0.        , -2.        ,  7.        ],
       [ 1.        ,  3.        , -1.        ,  5.        ,  7.        ]])

In [45]:
print(A,'\n\n',A.T)

[[ 2  1  1  0]
 [ 0 -1  4  1]
 [ 2  2  0 -2]
 [ 1  3 -1  5]] 

 [[ 2  0  2  1]
 [ 1 -1  2  3]
 [ 1  4  0 -1]
 [ 0  1 -2  5]]


In [48]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [49]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [55]:
print(A,'\n\n',
      A[2,2],'\n\n',
      A[1:,3],'\n\n',
      A[:,3],'\n\n',
      A[-2:,:],'\n\n',)

[[ 2  1  1  0]
 [ 0 -1  4  1]
 [ 2  2  0 -2]
 [ 1  3 -1  5]] 

 0 

 [ 1 -2  5] 

 [ 0  1 -2  5] 

 [[ 2  2  0 -2]
 [ 1  3 -1  5]] 




In [61]:
C = np.diag(v=np.array([1,2,3,4]),
            k=0)
print(C)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [67]:
A @ A

array([[ 6,  3,  6, -1],
       [ 9, 12, -5, -4],
       [ 2, -6, 12, -8],
       [ 5, 11,  8, 30]])

In [68]:
np.linalg.matrix_power(C,3)

array([[ 1,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0, 27,  0],
       [ 0,  0,  0, 64]])

In [77]:
#A*C
#vs
#A@C

In [76]:
#A**3
#vs
#np.linalg.matrix_power(A,3)

In [91]:
e_0 = np.resize(
    a=np.array([1,0,0,0]),
    new_shape=(4,1)
)
e_1 = np.resize(
    a=np.array([0,1,0,0]),
    new_shape=(4,1)
)
e_2 = np.resize(
    a=np.array([0,0,1,0]),
    new_shape=(4,1)
)
e_3 = np.resize(
    a=np.array([0,0,0,1]),
    new_shape=(4,1)
)

In [92]:
Column_matrix = np.concatenate((e_0,e_2,e_3),axis=1)
print(Column_matrix)

[[1 0 0]
 [0 0 0]
 [0 1 0]
 [0 0 1]]


In [95]:
#A@Column_matrix
#vs
#A[:,[0,2,3]]

array([[ 2,  1,  0],
       [ 0,  4,  1],
       [ 2,  0, -2],
       [ 1, -1,  5]])

In [96]:
Row_matrix = Column_matrix.T
print(Row_matrix)

[[1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [98]:
#Row_matrix@A
#vs
#A[[0,2,3],:]

array([[ 2,  1,  1,  0],
       [ 2,  2,  0, -2],
       [ 1,  3, -1,  5]])

¿Porqué?

Usando  que $(\boldsymbol{R S})^{T}=\boldsymbol{S}^{T} \boldsymbol{R}^{T}$. Sea $B=A^T$, con columnas $[b_j]$, notemos como:

$$
\left(\boldsymbol{b}_{j}\right)^{T}=\left(\boldsymbol{B} \boldsymbol{e}_{j}\right)^{T}=\boldsymbol{e}_{j}^{T} \boldsymbol{B}^{T}=\boldsymbol{e}_{j}^{T} \boldsymbol{A}
$$


In [103]:
#Row_matrix@A@Column_matrix
#vs
A[[0,2,3],:][:,[0,2,3]]

array([[ 2,  1,  0],
       [ 2,  0, -2],
       [ 1, -1,  5]])

Realize las siguientes operaciones elementales a $A$:

$$
\boldsymbol{A}=\left[\begin{array}{cccc}
2 & 1 & 1 & 0 \\
0 & -1 & 4 & 1 \\
2 & 2 & 0 & -2 \\
1 & 3 & -1 & 5
\end{array}\right]$$

* Multiplique el primer renglón por 0.5.
* Sume -2 veces el primer renglon al tercer renglón.
* Sume -1 vez el primer renglón al último renglón.

Haga lo mismo pero con la matriz aumentada, es decir,

$$A | v = \left[\begin{array}{cccc|c}
2 & 1 & 1 & 0 & \pi\\
0 & -1 & 4 & 1 & e\\
2 & 2 & 0 & -2 & 7\\
1 & 3 & -1 & 5 & 7
\end{array}\right]$$